### PR TITLE
Graphics for sample quest

### PR DESCRIPTION
**Pull request by Zefk**
I added what I mentioned on this post.
https://github.com/solarus-games/solarus-sample-quest/issues/5

### CODE REVIEW

**Comment by christopho** [comment]
Please only use lowecase filenames. Thanks

**Comment by Zefk** [comment]
Renamed the door and edited inside .dat to match it.

**Comment by Zefk** [comment]
I added table variations, shelf modifications, and female armor.

selection_001

castle tiles

**Comment by Zefk** [comment]
I went ahead and modded more tiles. I probably won't do more for quite some time. Enjoy!
selection_002
castle tiles

**Comment by Zefk** [comment]
I lied. I saw that the bookcase could be easily modded for resizing.

selection_001
selection_002
castle tiles

**Comment by Zefk** [comment]
Chair mods.

selection_001

**Comment by Zefk** [comment]
I added some dressers based on the bookcase. Oh, I made a pickaxe too.

selection_001

castle tiles

**Comment by Zefk** [comment]
Added Chests and wooden door.

selection_002

**Comment by Zefk** [comment]
Added switches. I made these switches. (CC0) They were modified based on the one I made for the book project.

selection_003

**Comment by Zefk** [comment]
Added leaver, solid switch, and two wall switches.

selection_001

**Comment by Zefk** [comment]
This will be the last mod for now. I modified the wood textures for the tables to make wooden floors, etc. The pictures can do the talking.

castle tiles

selection_001
selection_002
selection_003
selection_004

**Comment by Zefk** [comment]
I modified the log tiles further to fill in empty space.
castle tiles

selection_001

**Comment by Zefk** [comment]
1. I made a quick forest by further modding the castle tileset.
2. Sand, dirt, shallow water, and deep water. (CC0)
3. A few grass variations. (CC0)
4. Bushes/shrubs made by modding the castle tileset.

castle tiles
selection_001

**Comment by Zefk** [comment]
I fixed the water edges.

selection_001
castle tiles

**Comment by Zefk** [comment]
Added: Blended forest, rocks, waves, cactus, etc.

selection_001

castle tiles

**Comment by Zefk** [comment]
Added houses (modded the table into a house) and improved forest.
selection_001

castle tiles

**Comment by Zefk** [comment]
I found out how to resize the wooden house after some trial and error. The trees are looking okay.
selection_001

castle tiles

**Comment by christopho** [comment]
Thanks but this is supposed to be a castle interior tileset, why do you add trees and houses? These should be in another tileset.

**Comment by Diarandor** [comment]
I think Zefk is the perfect one to work on the sample quest and make a short demo-game from it.

**Comment by Zefk** [comment]
@christopho  I can put the forest on a separate tileset. 

@Diarandor  Well, I am making a chain quest (mixed quest) for the book project. I can easily adapt it for the sample quest when the book is done.

**Comment by Zefk** [comment]
I separated them. I left the cactus in the castle tileset because it could be used as a house plant and the vines could grow into the castle walls.

**Castle:**
castle tiles

**Forest:**

forest tiles

**Comment by Zefk** [comment]
I finished the desert tileset.

selection_001

desert tiles

**Comment by Zefk** [comment]
I think the forest and desert need ledges. I will make a desert door and adjust the forest door if I need to. At the moment I am working on making mushrooms.

**Comment by Zefk** [comment]
I made some resizable cliffs. I will adjust them a bit and submit them.
selection_001

**Comment by Zefk** [comment]
Added doors and cliffs.

green_small_door
wooden_small_door

**Preview:**
selection_002

**Desert:**
desert tiles

**Forest:**
forest tiles

**Comment by Zefk** [comment]
Added lower cliffs and made it possible for the player to go behind trees/stumps. I removed map design flaws and updated the sample maps as well. I think it is all good now.

selection_001

**Desert:**
desert tiles

**Forest:**
forest tiles

**Comment by Zefk** [comment]
**Added:**
I made the following.

+Whirlpool (CC0)
+Village floor bricks(CC0)
+Village grass walls - The design is CC0, but the flower & leaf textures are mods of the castle tileset pot.
+Store signs(CC0)
+Log tunnels(CC0) - I removed the CC-BY texture and add my own. I redesigned the log tunnel that I made for the Fairyolica world tileset to work correctly.
+Graveyard brick tiles(CC0)
+Gravestones(CC0)
+Fence(CC0)
+Log bridge(CC0)
+Stone bridge(CC0) - A thin redesign and color change of the Fairyolica World tileset bridge. (Color matches the graveyard)
+Mailbox (CC0)

selection_001

forest tiles

**Comment by Zefk** [comment]
I added whirlpools for the desert and different mushroom sizes for both tilesets.

**Desert:**
desert tiles

**Forest:**
forest tiles

**Pull request merged**
